apiVersion: v1
kind: Service
metadata:
  name: gflapi
  labels:
    app: gflapi
spec:
  ports:
  - name: apiport
    port: 8000
    
  
  
  selector:
    app: gflapi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gflapi-deploy
  labels:
    app: gflapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gflapi
  template:
    metadata:
      labels:
        app: gflapi
    spec:
      containers:
       - name: gflapi
         image: romanoa77/gflapi:alpha.k8s
         ports:
         - containerPort: 8000