apiVersion: v1
kind: Service
metadata:
  name: dslogic
  labels:
    app: dslogic
spec:
  ports:
  - name: dsport
    port: 5000
    
  
  
  selector:
    app: dslogic
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dslog-deploy
  labels:
    app: dslogic
  annotations:
   author: "Alessio Romano"
   mail: "alessio.romano329@edu.unito.it"
   descr: "Flask on gunicorn server app checking datastore state"
   other: "undergrad thesis university of Turin"  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dslogic
  template:
    metadata:
      labels:
        app: dslogic
    spec:
      containers:
       - name: dslogic
         image: romanoa77/dslogic:k8s.0.1.sync
         ports:
         - containerPort: 5000
         resources:
          requests:
            cpu: "2" 
            memory: "300Mi" 
